name: Docker CI workflow 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-build-dev:
    runs-on: ubuntu-latest
    name: Docker build test image
    steps:
      - uses: actions/checkout@v4

      - name: create docker image name
        id: dockerimage
        run: |
          DOKCER_TAG="testcandidates-$(date +%Y%m%d%H%M%S)"
          echo DOCKER_IMAGE="planthordev/identityserver:$DOKCER_TAG" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:      
          file: ./Dockerfile
          tags: ${{ steps.dockerimage.outputs.DOCKER_IMAGE }}
          github-token: ${{ github.token }}
          push: false

  docker-build-prod:
    runs-on: ubuntu-latest
    name: Docker build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: create docker image name
        id: dockerimage
        run: |
          DOKCER_TAG="testcandidates-$(date +%Y%m%d%H%M%S)"
          echo DOCKER_IMAGE="planthordev/identityserver:$DOKCER_TAG" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.1.0
        with:      
          file: ./Dockerfile
          tags: ${{ steps.dockerimage.outputs.DOCKER_IMAGE }}
          github-token: ${{ github.token }}
          push: true
                