name: Docker CI workflow 

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Docker build
    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          # provided by @akakshuki
          # TODO: change to technical user account in the future
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: create docker image name
        id: dockerimage
        run: |
          DOKCER_TAG="testcandidates-$(date +%Y%m%d%H%M%S)"
          echo DOCKER_IMAGE="trunglepham1202/planthor-clientfrontendwebapp:$DOKCER_TAG" >> "$GITHUB_OUTPUT"

      - name: docker build image
        run: |
         docker buildx build -t $DOCKER_IMAGE .
        env:
          DOCKER_IMAGE: ${{ steps.dockerimage.outputs.DOCKER_IMAGE }}

      - name: push image to docker hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker images
          docker push $DOCKER_IMAGE
        env:
            DOCKER_IMAGE: ${{ steps.dockerimage.outputs.DOCKER_IMAGE }}

 