name: Code Analysis

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  coverage:
    name: Run Coverage 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Restore dependencies
        run: dotnet restore

      - name: run coverage code 
        run: |
          dotnet tool install --global dotnet-coverage
          dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./coverage.xml

  sonar-scan:
    name: Run SonarScanner
    runs-on: ubuntu-22.04
    needs: [ coverage ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: ./coverage.xml

      - name: Analyze with SonarQube
        uses: SonarSource/sonarqube-scan-action@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args:
            -Dsonar.projectKey=Planthor_PlanthorIdentityServer
            -Dsonar.organization=planthor
            -Dsonar.tests=./coverage.xml
